### ISSUE TITLE
How can get AuthResponse data?

### ISSUE THREAD

**Issue by paula23andrea** [vertcitron/vue-google-api#1]
Is there some method for getting [AuthResponse](https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleusergetauthresponseincludeauthorizationdata) data ? 

I found It is on [_guser_](https://github.com/vertcitron/vue-google-api/blob/6b0a9c8b1dc01c18fb22637daea11966c18be931/src/core/gapi.js#L30), but the method only returns basicProfile info.

**Comment by vertcitron** [comment]
Excuse me, I was traveling, so it has been a little bit long for me to respond...
The auth service from Google will never give you more than a basic profile.
To get the complete profile, you have to request the People API with the id you got.
A authenticated user can normally get via People API the complete profile for him/herself, and his/her contacts registered on Google.
