### ISSUE TITLE
Is there any easy way to get access_token?

### ISSUE THREAD

**Issue by Robert-Dawidowski** [vertcitron/vue-google-api#16]
Is there any easy way to get granted access_token after successful signin?

**Comment by Robert-Dawidowski** [comment]
i found solution if someone want:

`let GoogleAuth;
 let GoogleUser;
 this.$gapi._libraryLoad('auth2')
    .then(auth2 => {
       auth2.init(this.$gapi.config);
       GoogleAuth = auth2.getAuthInstance();
       GoogleUser = GoogleAuth.currentUser.get();
       return GoogleUser.uc.access_token;
  })`

**Comment by mcasto** [comment]
FYI, I found a similar solution by doing an end run around the wrapper with:

`var access_token = window.gapi.auth2.getAuthInstance().currentUser.je.uc.access_token;`
