### ISSUE TITLE
authresponce access

### ISSUE THREAD

**Issue by epam20** [vertcitron/vue-google-api#3]
Hi there,

I just found your google-api wrapper and I believe it's a very nice tool. However, after doing some reading on  [Google Sign-In](https://developers.google.com/identity/sign-in/web/sign-in) I believe that there are some missing parts you need to add to it.

Is it possible you either add auth.currentUser.get().getAuthResponse() somewhere so I can access it or at least expose its contents into an object of your own? There's plenty of other information that is useful in there, such as access and id tokens, expires in and at, token type etc.

Maybe it would be even better if you expose the "auth" object to me so I can handle it the way I want.

Hope you are on to that or getting there. I would appreciate it much.

thanks

**Comment by vertcitron** [comment]
I added in the GAPI class a function returning the `auth` object.
This function is `getAuthObject` to satisfy what you said, but in fact, it was just a call to `_libraryInit('auth2`)`, but I agree that this function has the vocation to stay private...
